import Script from "next/script";
import '../../styles/globals.css'
import Head from "next/head";
import localFont from "next/font/local";
import { Inter } from "next/font/google";

const NeueMontreal = localFont({
  src: '../../public/assets/PPNeueMontreal-Regular.woff',
})
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wonjun Jang',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Wonjun Jang</title>
      </Head>
      <Script
        src={`https://www.googletagmanager.com/gtag/js?id=${
          process.env.GA_ID || process.env.NEXT_PUBLIC_GA_ID
        }`}
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
         window.dataLayer = window.dataLayer || [];
         function gtag(){window.dataLayer.push(arguments);}
         gtag('js', new Date());

         gtag('config', '${
           process.env.GA_ID || process.env.NEXT_PUBLIC_GA_ID
         }');
        `}
      </Script>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
